name: Sync external metadata
on: 
  workflow_dispatch:
  schedule:
    # This cron expression means: Run at 12:00 PM (noon) UTC every day
    # The format is: minute hour day-of-month month day-of-week
    # '0 12 * * *' = At minute 0 of hour 12 (noon) on any day of month, any month, any day of week
    - cron: '0 8,20 * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run sync-external-metadata
        env:
          DATO_API_TOKEN: ${{ secrets.DATO_API_TOKEN }}
          DATO_API_KEY_NL2120: ${{ secrets.DATO_API_KEY_NL2120 }}
          DATO_API_KEY_OPENEARTH_RWS_VIEWER: ${{ secrets.DATO_API_KEY_OPENEARTH_RWS_VIEWER }}
